=== Cassandra-Kaye-Honrada/ipt_endterm/wwwroot/Schemas/products.dtd
<!ELEMENT Products (Product+)>
<!ELEMENT Product (ProductId, ProductName, Description, BasePrice, Stock, ImageUrl, Status, CategoryName)>
<!ELEMENT ProductId (#PCDATA)>
<!ELEMENT ProductName (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT BasePrice (#PCDATA)>
<!ELEMENT Stock (#PCDATA)>
<!ELEMENT ImageUrl (#PCDATA)>
<!ELEMENT Status (#PCDATA)>
<!ELEMENT CategoryName (#PCDATA)>

=== Cassandra-Kaye-Honrada/ipt_endterm/wwwroot/Schemas/products.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Products SYSTEM "products.dtd">
<Products>
  <Product>
    <ProductId>8</ProductId>
    <ProductName>1</ProductName>
    <Description>1</Description>
    <BasePrice>1.00</BasePrice>
    <Stock>0</Stock>
    <ImageUrl>1</ImageUrl>
    <Status>Available</Status>
    <CategoryName>1</CategoryName>
  </Product>
</Products>
